# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet

on:
  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore all dependencies
        run: dotnet restore
      - name: Build QuadrupleLib.Tests
        run: dotnet build QuadrupleLib.Tests --no-restore --framework net10.0
      - name: Test QuadrupleLib
        run: dotnet test --no-build --verbosity normal --framework net10.0
      - name: Build QuadrupleLib (Release)
        run: dotnet build QuadrupleLib --no-restore --configuration Release
      - name: Create NuGet packages
        run: dotnet pack --no-build --output build/
      - name: Publish to NuGet
        run: dotnet nuget push --api-key ${{ secrets.API_KEY }} --source nuget.org build/**/*.nupkg
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
